### ISSUE TITLE
Czy możesz usunąć odnośniki do https://cryptowat.ch ?

### ISSUE THREAD

**Issue by klojniewski** [Pagepro/arbitrage-frontend#10]
Link do giełdy potrzebny jest do tego, żeby do niej przejść i złożyć zlecenie zakupu lub sprzedaży.
https://cryptowat.ch nie jest giełdą, tylko jest appką monitorującą rynki, dlatego ten link jest błędny.

Jeśli nie da się zrobić linku do konkretnej waluty, zrób po prostu link do strony głównej giełdy.

**Comment by Patryk-Komar** [comment]
Zrobione.
