### ISSUE TITLE
Classa "updated" nie jest zdejmowana

### ISSUE THREAD

**Issue by klojniewski** [Pagepro/arbitrage-frontend#7]
Wydaje mi się, że wszystko jest na żółto bo classa updated nie jest zdejmowana po "x" sekundach.
Sprawdź proszę czy to problem w kodzie czy nigdy nie upływają "x" sekundy bo jest nowy update.

**Comment by Patryk-Komar** [comment]
Zgadza się, klasa nie była zdejmowana.

Teraz wszystko działa i odświeża się elegancko.
